name: Validate CircleCI Configuration

on:
  push:
    paths:
      - '.circleci/**'
  pull_request:
    paths:
      - '.circleci/**'
  workflow_dispatch:

jobs:
  validate-circleci-config:
    runs-on: ubuntu-latest
    name: Validate CircleCI Configuration
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install CircleCI CLI
        run: |
          curl -fLSs https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/main/install.sh | bash
          
      - name: Validate CircleCI configuration
        run: |
          echo "🔍 Validating CircleCI configuration syntax..."
          circleci config validate .circleci/config.yml
          echo "✅ CircleCI configuration is valid!"
          
      - name: Run validation script
        run: |
          chmod +x scripts/validate-circleci.sh
          ./scripts/validate-circleci.sh
          
      - name: Check for orb updates
        run: |
          echo "🔍 Checking for potential orb updates..."
          echo "Current Node.js orb: circleci/node@5.1.0"
          echo "Current Python orb: circleci/python@2.1.1"
          echo "💡 Consider checking for newer versions at: https://circleci.com/developer/orbs"
